import type {Metadata} from "next";

export const metadata: Metadata = {
    title: "Админ панель",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body>
        <div className={'min-h-screen bg-background'}>
            {children}
        </div>
        </body>
        </html>
    );
}
