import type {Metadata} from "next";

import {Balsamiq_Sans} from "next/font/google";

import "../globals.css";

import {Header} from "@/widgets/header";
import {Footer} from "@/widgets/footer";

const geistMono = Balsamiq_Sans({
    variable: "--font-geist-mono",
    subsets: ["latin"],
    weight: '400'
});

export const metadata: Metadata = {
    title: "Алексей Коростов | Портфолио",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${geistMono.variable} antialiased`}
        >
        <div className={'min-h-screen bg-background'}>
            <Header/>
            {children}
            <Footer/>
        </div>
        </body>
        </html>
    );
}
