import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import {Header} from "@/widgets/header";

const geistMono = Ubuntu({
  variable: "--font-geist-mono",
  subsets: ["latin"],
    weight: '300'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistMono.variable} antialiased`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
